### ISSUE TITLE
`org.jenkinsci.plugins.pipeline.modeldefinition.TriggersTest` tends to run out of memory

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#1364]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04 LTS x86_64

### Reproduction steps

Remove the exclusion for `org.jenkinsci.plugins.pipeline.modeldefinition.TriggersTest` in `excludes.txt` added in https://github.com/jenkinsci/bom/pull/1359, then run the test suite a few times.

### Expected Results

The tests should reliably pass.

### Actual Results

`org.jenkinsci.plugins.pipeline.modeldefinition.TriggersTest` tends to run out of memory and crash with exit code 137.

**Comment by basil** [comment]
Also seen in `MatrixTest`, even when starting PCT with `-Xmx256m`:

```
[2022-07-29T21:33:32.900Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-cli) on project pipeline-model-definition: There are test failures.
[2022-07-29T21:33:32.900Z] [ERROR] 
[2022-07-29T21:33:32.900Z] [ERROR] Please refer to /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire-reports for the individual test results.
[2022-07-29T21:33:32.900Z] [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[2022-07-29T21:33:32.900Z] [ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2022-07-29T21:33:32.900Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition && /opt/java/openjdk/bin/java -Djava.awt.headless=true -Xmx4g -Xms512m -XX:MaxPermSize=512m -jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire/surefirebooter2696290997866732736.jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire 2022-07-29T21-23-15_596-jvmRun1 surefire13473258767266335827tmp surefire_214831249492347844298tmp
[2022-07-29T21:33:32.901Z] [ERROR] Error occurred in starting fork, check output in log
[2022-07-29T21:33:32.901Z] [ERROR] Process Exit Code: 137
[2022-07-29T21:33:32.901Z] [ERROR] Crashed tests:
[2022-07-29T21:33:32.901Z] [ERROR] org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest
[2022-07-29T21:33:32.901Z] [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2022-07-29T21:33:32.901Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition && /opt/java/openjdk/bin/java -Djava.awt.headless=true -Xmx4g -Xms512m -XX:MaxPermSize=512m -jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire/surefirebooter2696290997866732736.jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire 2022-07-29T21-23-15_596-jvmRun1 surefire13473258767266335827tmp surefire_214831249492347844298tmp
[2022-07-29T21:33:32.901Z] [ERROR] Error occurred in starting fork, check output in log
[2022-07-29T21:33:32.901Z] [ERROR] Process Exit Code: 137
[2022-07-29T21:33:32.901Z] [ERROR] Crashed tests:
[2022-07-29T21:33:32.901Z] [ERROR] org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:385)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:300)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:249)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[2022-07-29T21:33:32.901Z] [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[2022-07-29T21:33:32.901Z] [ERROR] Command was /bin/sh -c cd /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition && /opt/java/openjdk/bin/java -Djava.awt.headless=true -Xmx4g -Xms512m -XX:MaxPermSize=512m -jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire/surefirebooter2696290997866732736.jar /home/jenkins/workspace/Tools_bom_PR-1365/pct-work/pipeline-model-definition/pipeline-model-definition/target/surefire 2022-07-29T21-23-15_596-jvmRun1 surefire13473258767266335827tmp surefire_214831249492347844298tmp
[2022-07-29T21:33:32.901Z] [ERROR] Error occurred in starting fork, check output in log
[2022-07-29T21:33:32.901Z] [ERROR] Process Exit Code: 137
[2022-07-29T21:33:32.901Z] [ERROR] Crashed tests:
[2022-07-29T21:33:32.901Z] [ERROR] org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:690)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:374)
[2022-07-29T21:33:32.901Z] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:350)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-07-29T21:33:32.901Z] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-07-29T21:33:32.901Z] [ERROR] -> [Help 1]
[2022-07-29T21:33:32.901Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-cli) on project pipeline-model-definition: There are test failures.
```
