### ISSUE TITLE
config-file-provider plugin fails MavenSettingsConfigTest.freestyleWithCredentials test

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#2513]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Profiles 2.414.x, 2.401.x, and 2.387.x all fail the `MavenSettingsConfigTest.freestyleWithCredentials`  test .

The weekly profile does not fail the `MavenSettingsConfigTest.freestyleWithCredentials1  test 
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux with Java versions 11 or 21

### Reproduction steps

1. Checkout [PR 2512](https://github.com/jenkinsci/bom/pull/2512) and run  `LINE=2.401.x PLUGINS=config-file-provider TEST=MavenSettingsConfigTest bash local-test.sh`
2. Confirm that the tests fail with the stack trace:

```text
[ERROR] org.jenkinsci.plugins.configfiles.maven.MavenSettingsConfigTest.freestyleWithCredentials -- Time elapsed: 8.398 s <<< ERROR!
java.io.IOException: Illegal base64 character -1
        at java.base/java.util.Base64$DecInputStream.read(Base64.java:1016)
        at java.base/java.io.DataInputStream.read(DataInputStream.java:149)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
        at hudson.util.IOUtils.skip(IOUtils.java:90)
        at hudson.console.ConsoleNote.skip(ConsoleNote.java:309)
        at hudson.console.PlainTextConsoleOutputStream.eol(PlainTextConsoleOutputStream.java:67)
        at hudson.console.LineTransformationOutputStream.eol(LineTransformationOutputStream.java:61)
        at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:57)
        at hudson.console.LineTransformationOutputStream.write(LineTransformationOutputStream.java:75)
        at org.apache.commons.io.output.ProxyOutputStream.write(ProxyOutputStream.java:92)
        at org.kohsuke.stapler.framework.io.LargeText.writeLogTo(LargeText.java:233)
        at hudson.console.AnnotatedLargeText.writeLogTo(AnnotatedLargeText.java:164)
        at org.jvnet.hudson.test.JenkinsRule.getLog(JenkinsRule.java:1529)
        at org.jvnet.hudson.test.JenkinsRule.assertLogNotContains(JenkinsRule.java:1518)
        at org.jenkinsci.plugins.configfiles.maven.MavenSettingsConfigTest.freestyleWithCredentials(MavenSettingsConfigTest.java:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:606)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

### Expected Results

Test should pass on the older lines just as they pass on the weekly line

### Actual Results

Test fails with an `Illegal base64 character: -1`

**Comment by MarkEWaite** [comment]
I've started a bisect to see if I can identify a commit to the bill of materials that first shows the failure.  I still don't understand how the failure is happening, but maybe the bisect will guide the investigation more effectively than my guessing has.

**Comment by MarkEWaite** [comment]
The most recent release of the credentials binding plugin causes the config-file-provider test failure on the LTS versions (2.414.x, 2.401.x, and 2.387.x).  The failure does not appear on the weekly release 2.423.

@Kevin-CB would you be willing to investigate the interaction between the base64 credentials masking and the config-file-provider plugin tests?  I am reasonably confident that the change came from:

* https://github.com/jenkinsci/credentials-binding-plugin/pull/269

I've proposed a pull request to the plugin bill of materials to work around it so that we can release a plugin bill of materials before the end of the week, but would like to remove that workaround in the future.
