### ISSUE TITLE
`org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest#loaderReleased` is flaky

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#2658]
Observed a failure in https://github.com/jenkinsci/bom/pull/2655/checks?check_run_id=18643349699 in `org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest#loaderReleased`:

```
java.lang.AssertionError: 
{org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3=static final java.util.concurrent.ForkJoinPool java.util.concurrent.ForkJoinPool.common->
java.util.concurrent.ForkJoinPool@3badfecc-queues->
[Ljava.util.concurrent.ForkJoinPool$WorkQueue;@69955964-[3]->
java.util.concurrent.ForkJoinPool$WorkQueue@85db49a-owner->
java.util.concurrent.ForkJoinWorkerThread@78c1d6a7-inheritedAccessControlContext->
java.security.AccessControlContext@571d981c-context->
[Ljava.security.ProtectionDomain;@6a6b4de5-[14]->
java.security.ProtectionDomain@3b9a0b17-classloader->
org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3}
	at org.junit.Assert.fail(Assert.java:89)
	at org.jvnet.hudson.test.MemoryAssert.assertGC(MemoryAssert.java:211)
	at org.jvnet.hudson.test.MemoryAssert.assertGC(MemoryAssert.java:149)
	at org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest.loaderReleased(LibraryMemoryTest.java:85)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:607)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

From standard error:

```
  14.291 [p #1] [Pipeline] Start of Pipeline
registering WorkflowScript@52cd846f
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader@35033c7a
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@124b8d74
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader@25eee7d5
…from org.jenkinsci.plugins.workflow.cps.GroovySourceFileAllowlist$ClassLoaderImpl@24462138
…from org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxResolvingClassLoader@500d3630
  14.493 [p #1] [Pipeline] node
  14.543 [p #1] Running on Jenkins in /home/jenkins/agent/workspace/Tools_bom_PR-2655/target/pct-work/pipeline-groovy-lib-plugin/target/tmp/j h13732391855676351643/workspace/p
  14.594 [p #1] [Pipeline] {
  14.644 [p #1] [Pipeline] }
  14.644 [p #1] [Pipeline] // node
registering leak@e550996
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@124b8d74
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader@25eee7d5
…from org.jenkinsci.plugins.workflow.cps.GroovySourceFileAllowlist$ClassLoaderImpl@24462138
…from org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxResolvingClassLoader@500d3630
registering p.C@702b98c2
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@124b8d74
…from org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$TimingLoader@25eee7d5
…from org.jenkinsci.plugins.workflow.cps.GroovySourceFileAllowlist$ClassLoaderImpl@24462138
…from org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxResolvingClassLoader@500d3630
  14.661 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#optimizeStorage: Migrating CpsFlowExecution[Owner[p/1:p #1]] to BulkFlowNodeStorage
  14.672 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#optimizeStorage: Copied nodes to workflow-completed
  14.672 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#optimizeStorage: Deleted /home/jenkins/agent/workspace/Tools_bom_PR-2655/target/pct-work/pipeline-groovy-lib-plugin/target/tmp/j h13732391855676351643/jobs/p/builds/1/workflow
  14.679 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#cleanUpHeap: cleanUpHeap on Owner[p/1:p #1]
  14.680 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#closeShells: closing main class loader from Owner[p/1:p #1]
  14.680 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#closeShells: closing trusted class loader from Owner[p/1:p #1]
  14.680 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: ignoring org.jenkinsci.plugins.workflow.cps.GroovySourceFileAllowlist$ClassLoaderImpl@24462138
  14.680 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: found org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@124b8d74
  14.682 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#cleanUpGlobalClassValue: cleaning up [class p.C, class leak] associated with org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@124b8d74
  14.683 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: found leak
  14.683 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpClassHelperCache: cleaning up leak from ClassHelperCache? false
  14.683 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: found p.C
  14.683 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpClassHelperCache: cleaning up p.C from ClassHelperCache? true
  14.683 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: found org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3
  14.684 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#cleanUpGlobalClassValue: cleaning up [class WorkflowScript] associated with org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3
  14.684 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpLoader: found WorkflowScript
  14.684 [id=155]	FINER	o.j.p.w.cps.CpsFlowExecution#cleanUpClassHelperCache: cleaning up WorkflowScript from ClassHelperCache? false
  14.695 [p #1] [Pipeline] End of Pipeline
  14.721 [p #1] Finished: SUCCESS
  14.722 [id=155]	FINE	o.j.p.w.cps.CpsFlowExecution#logTimings: timings for Owner[p/1:p #1]: {classLoad=1775ms, flowNode=34ms, parse=1413ms, run=412ms, saveProgram=99ms}
Trying to collect org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3…
GC after allocation of size 1331
GC after allocation of size 1730
GC after allocation of size 2249
GC after allocation of size 2923
GC after allocation of size 3799
GC after allocation of size 4938
GC after allocation of size 6419
GC after allocation of size 8344
GC after allocation of size 10847
GC after allocation of size 14101
GC after allocation of size 18331
GC after allocation of size 23830
GC after allocation of size 30979
GC after allocation of size 40272
GC after allocation of size 52353
GC after allocation of size 68058
GC after allocation of size 88475
GC after allocation of size 115017
GC after allocation of size 149522
GC after allocation of size 194378
GC after allocation of size 252691
GC after allocation of size 328498
GC after allocation of size 427047
GC after allocation of size 555161
GC after allocation of size 721709
GC after allocation of size 938221
GC after allocation of size 1219687
GC after allocation of size 1585593
GC after allocation of size 2061270
GC after allocation of size 2679651
GC after allocation of size 3483546
GC after allocation of size 4528609
GC after allocation of size 5887191
GC after allocation of size 7653348
GC after allocation of size 9949352
GC after allocation of size 12934157
GC after allocation of size 16814404
GC after allocation of size 21858725
GC after allocation of size 28416342
GC after allocation of size 36941244
GC after allocation of size 48023617
Failed to collect org.jenkinsci.plugins.workflow.cps.CpsGroovyShell$CleanGroovyClassLoader@769578f3, looking for strong references…
[…]
  27.516 [id=30]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
```

I could not reproduce this locally. However, running the test locally I can see we use `ForkJoinPool#common` via Caffeine in a few contexts:

- `jenkins.branch.WorkspaceLocatorImpl`
- `org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage`
- `org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxResolvingClassLoader`

Of these the last seems to be the most likely culprit, as its stack trace includes `GroovyClassLoader` (of which the `CleanGroovyClassLoader` mentioned above is a subclass):

```
commonPool:2798, ForkJoinPool (java.util.concurrent)
getExecutor:337, Caffeine (com.github.benmanes.caffeine.cache)
<init>:265, BoundedLocalCache (com.github.benmanes.caffeine.cache)
<init>:-1, SS (com.github.benmanes.caffeine.cache)
<init>:-1, SSS (com.github.benmanes.caffeine.cache)
<init>:-1, SSSW (com.github.benmanes.caffeine.cache)
newInstance:-1, SSSW$$Lambda/0x00007ff61c738218 (com.github.benmanes.caffeine.cache)
newBoundedLocalCache:48, LocalCacheFactory (com.github.benmanes.caffeine.cache)
<init>:3953, BoundedLocalCache$BoundedLocalManualCache (com.github.benmanes.caffeine.cache)
<init>:3949, BoundedLocalCache$BoundedLocalManualCache (com.github.benmanes.caffeine.cache)
build:1048, Caffeine (com.github.benmanes.caffeine.cache)
lambda$makeParentCache$3:112, SandboxResolvingClassLoader (org.jenkinsci.plugins.scriptsecurity.sandbox.groovy)
load:-1, SandboxResolvingClassLoader$$Lambda/0x00007ff61c6b7198 (org.jenkinsci.plugins.scriptsecurity.sandbox.groovy)
lambda$newMappingFunction$3:183, LocalLoadingCache (com.github.benmanes.caffeine.cache)
apply:-1, LocalLoadingCache$$Lambda/0x00007ff61c687b80 (com.github.benmanes.caffeine.cache)
lambda$statsAware$2:167, LocalCache (com.github.benmanes.caffeine.cache)
apply:-1, LocalCache$$Lambda/0x00007ff61c6d6c08 (com.github.benmanes.caffeine.cache)
lambda$doComputeIfAbsent$14:2688, BoundedLocalCache (com.github.benmanes.caffeine.cache)
apply:-1, BoundedLocalCache$$Lambda/0x00007ff61c68a038 (com.github.benmanes.caffeine.cache)
compute:1916, ConcurrentHashMap (java.util.concurrent)
doComputeIfAbsent:2686, BoundedLocalCache (com.github.benmanes.caffeine.cache)
computeIfAbsent:2669, BoundedLocalCache (com.github.benmanes.caffeine.cache)
computeIfAbsent:112, LocalCache (com.github.benmanes.caffeine.cache)
get:58, LocalLoadingCache (com.github.benmanes.caffeine.cache)
load:78, SandboxResolvingClassLoader (org.jenkinsci.plugins.scriptsecurity.sandbox.groovy)
getResource:73, SandboxResolvingClassLoader (org.jenkinsci.plugins.scriptsecurity.sandbox.groovy)
getResource:1413, ClassLoader (java.lang)
getResource:112, GroovySourceFileAllowlist$ClassLoaderImpl (org.jenkinsci.plugins.workflow.cps)
getResource:1413, ClassLoader (java.lang)
getResource:223, CpsGroovyShell$TimingLoader (org.jenkinsci.plugins.workflow.cps)
getResource:1413, ClassLoader (java.lang)
getSourceFile:888, GroovyClassLoader (groovy.lang)
access$100:87, GroovyClassLoader (groovy.lang)
run:112, GroovyClassLoader$1$1 (groovy.lang)
run:108, GroovyClassLoader$1$1 (groovy.lang)
executePrivileged:778, AccessController (java.security)
doPrivileged:319, AccessController (java.security)
loadGroovySource:108, GroovyClassLoader$1 (groovy.lang)
loadClass:739, GroovyClassLoader (groovy.lang)
loadClass:812, GroovyClassLoader (groovy.lang)
loadClass:580, ClassLoader (java.lang)
loadClass:218, CpsGroovyShell$TimingLoader (org.jenkinsci.plugins.workflow.cps)
loadClass:580, ClassLoader (java.lang)
loadClass:702, GroovyClassLoader (groovy.lang)
loadClass:570, GroovyClassLoader (groovy.lang)
tryAsLoaderClassOrScript:184, ClassNodeResolver (org.codehaus.groovy.control)
findClassNode:169, ClassNodeResolver (org.codehaus.groovy.control)
resolveName:125, ClassNodeResolver (org.codehaus.groovy.control)
resolveToOuter:740, ResolveVisitor (org.codehaus.groovy.control)
resolve:377, ResolveVisitor (org.codehaus.groovy.control)
resolveFromDefaultImports:518, ResolveVisitor (org.codehaus.groovy.control)
resolve:375, ResolveVisitor (org.codehaus.groovy.control)
resolveFromStaticInnerClasses:493, ResolveVisitor (org.codehaus.groovy.control)
resolve:376, ResolveVisitor (org.codehaus.groovy.control)
resolveFromStaticInnerClasses:493, ResolveVisitor (org.codehaus.groovy.control)
resolve:376, ResolveVisitor (org.codehaus.groovy.control)
resolveFromStaticInnerClasses:493, ResolveVisitor (org.codehaus.groovy.control)
resolve:376, ResolveVisitor (org.codehaus.groovy.control)
resolveFromStaticInnerClasses:493, ResolveVisitor (org.codehaus.groovy.control)
resolve:376, ResolveVisitor (org.codehaus.groovy.control)
resolveFromStaticInnerClasses:493, ResolveVisitor (org.codehaus.groovy.control)
resolve:376, ResolveVisitor (org.codehaus.groovy.control)
visitClass:1302, ResolveVisitor (org.codehaus.groovy.control)
startResolving:214, ResolveVisitor (org.codehaus.groovy.control)
call:684, CompilationUnit$12 (org.codehaus.groovy.control)
applyToSourceUnits:966, CompilationUnit (org.codehaus.groovy.control)
doPhaseOperation:626, CompilationUnit (org.codehaus.groovy.control)
compile:575, CompilationUnit (org.codehaus.groovy.control)
doParseClass:323, GroovyClassLoader (groovy.lang)
parseClass:293, GroovyClassLoader (groovy.lang)
parse:163, GroovySandbox$Scope (org.jenkinsci.plugins.scriptsecurity.sandbox.groovy)
doParse:190, CpsGroovyShell (org.jenkinsci.plugins.workflow.cps)
reparse:175, CpsGroovyShell (org.jenkinsci.plugins.workflow.cps)
parseScript:635, CpsFlowExecution (org.jenkinsci.plugins.workflow.cps)
start:581, CpsFlowExecution (org.jenkinsci.plugins.workflow.cps)
run:335, WorkflowRun (org.jenkinsci.plugins.workflow.job)
execute:101, ResourceController (hudson.model)
run:442, Executor (hudson.model)
```

Later on some cleanup work on `SandboxResolvingClassLoader` happens when the test succeeds:

```
commonPool:2798, ForkJoinPool (java.util.concurrent)
rescheduleCleanUpIfIncomplete:1680, BoundedLocalCache (com.github.benmanes.caffeine.cache)
performCleanUp:1664, BoundedLocalCache (com.github.benmanes.caffeine.cache)
run:3886, BoundedLocalCache$PerformCleanupTask (com.github.benmanes.caffeine.cache)
exec:3873, BoundedLocalCache$PerformCleanupTask (com.github.benmanes.caffeine.cache)
doExec:387, ForkJoinTask (java.util.concurrent)
topLevelExec:1312, ForkJoinPool$WorkQueue (java.util.concurrent)
scan:1843, ForkJoinPool (java.util.concurrent)
runWorker:1808, ForkJoinPool (java.util.concurrent)
run:188, ForkJoinWorkerThread (java.util.concurrent)
```

My initial theory is that when the test fails, this cleanup work might be happening too late, by which point the test has already failed. [This page](https://github.com/ben-manes/caffeine/wiki/Cleanup) seems to support the theory:

> The scheduling is best-effort and does not make any hard guarantees of when an expired entry will be removed.

The page goes on to recommend two other ways of ensuring prompt removal of cache entries: the system-wide scheduling thread or a dedicated `Cleaner`. Of course testing the implementation of any fix would be quite difficult, since the problem is not readily reproducible. Perhaps the problem could be reproduced with a hacked version of Caffeine that doesn't do regular maintenance and therefore would rely on the system-wide scheduling thread or a dedicated `Cleaner` in order to clean anything at all.

**Comment by basil** [comment]
I have filed [JENKINS-72325](https://issues.jenkins.io/browse/JENKINS-72325) to track this issue.
