### ISSUE TITLE
Remove the script-security 1310.vf24a_dfce068b_ block

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#2805]
### Jenkins and plugins versions report

Test failure can be seen with script security 1310.vf24a_dfce068b_:

```
LINE=2.426.x PLUGINS=script-security TEST=ScriptApprovalLoadingTest bash local-test.sh
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Run the test with script  security plugin 1310.x and this command:
```
LINE=2.426.x PLUGINS=script-security TEST=ScriptApprovalLoadingTest bash local-test.sh
```

### Expected Results

Once a test with a more recent release of script-security is passing, then the script-security exclusion in the .github/dependabot.yml file should be removed.

### Actual Results

Test fails unexpectedly

### Anything else?

I've asked for help from @jglick in https://github.com/jenkinsci/script-security-plugin/pull/552#issuecomment-1879780192

**Comment by jglick** [comment]
```
org.jvnet.hudson.test.RealJenkinsRule$StepException: Remote step threw an exception: jenkins.RestartRequiredException
	at org.jvnet.hudson.test.RealJenkinsRule.runRemotely(RealJenkinsRule.java:916)
	at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:661)
	at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:652)
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApprovalLoadingTest.dynamicLoading(ScriptApprovalLoadingTest.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jvnet.hudson.test.RealJenkinsRule$1.evaluate(RealJenkinsRule.java:488)
Caused by: jenkins.RestartRequiredException
	at hudson.PluginManager.dynamicLoad(PluginManager.java:922)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:892)
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApprovalLoadingTest._dynamicLoading2(ScriptApprovalLoadingTest.java:54)
```

I think this is a PCT-only issue. Have to think about how to simply skip this test in PCT.
