### ISSUE TITLE
`WorkflowRunRestartTest` had been ignored for one reason but is now failing for another reason

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#611]
### Reproduction steps

- Remove any exclusions for `WorkflowRunRestartTest`, if any remain in the source tree.
- Run: `PLUGINS=workflow-job TEST=org.jenkinsci.plugins.workflow.job.WorkflowRunRestartTest#interruptedWhileStartingPerformanceOptimized,org.jenkinsci.plugins.workflow.job.WorkflowRunRestartTest#interruptedWhileStartingMaxSurvivability bash local-test.sh`

### Results

This regression went noticed because these test results were being ignored for a different reason (jenkinsci/workflow-job-plugin#158). That PR was closed because the underlying problem was fixed, but the test results were never un-ignored, so this new regression slipped by unnoticed.

These two tests now fail with:

```java
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: -1: unable to resolve class org.jenkinsci.plugins.workflow.libs.Library
 @ line -1, column -1.
1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
        at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
        at groovy.lang.GroovyShell$evaluate.call(Unknown Source)
```

**Comment by jglick** [comment]
https://github.com/jenkinsci/workflow-job-plugin/pull/208 ought to work around the failure.

**Comment by timja** [comment]
-.- https://github.com/jenkinsci/workflow-job-plugin/pull/235/files#r790120628

**Comment by jglick** [comment]
Need to actually remove https://github.com/jenkinsci/bom/blob/c436d7fc6bdcbf0d0841acd296819b1f7823bed1/excludes.txt#L16-L17
