### ISSUE TITLE
`org.jenkinsci.plugins.pipeline.modeldefinition.BasicModelDefTest` and `org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest` are too unstable

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#613]
In this repository, we set `surefire.rerunFailingTestsCount=4` to run failing tests up to 4 times, and we also have a `retry(2)` block in the `Jenkinsfile`. A test that manages to fail despite all of this is too flaky to be included in the suite. We recently excluded `org.jenkinsci.plugins.pipeline.modeldefinition.BasicModelDefTest` and `org.jenkinsci.plugins.pipeline.modeldefinition.MatrixTest` from the suite because they were causing too many problems for unrelated PRs. We should try re-enabling those tests in a new PR and investigate how to get them to pass reliably again.

**Comment by jglick** [comment]
CC @car-roll and/or @bitwiseman

**Comment by timja** [comment]
Experimenting over here with declarative builds: https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/454

Looks like that repo runs on VMs not container builds.

Specs:

Container:
CPU: 4
Memory: 8gb

VM:
https://aws.amazon.com/ec2/instance-types/t3/
t3.xlarge

CPU: 4
Memory: 16gb

**Comment by timja** [comment]
Weird, 3 builds in a row pass in that repo directly using container agents.

Maybe something to do with PCT and resource allocation

**Comment by jglick** [comment]
I suspect problematic test cases. E.g. https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/355

> Tests have been added to cover the new scenarios, but not all of them can run in CI and not time out.

or https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/master/pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/BasicModelDefTest.java#L77-L136

@bitwiseman perhaps the heavyweight tests could be marked with a JUnit category that lets them get run only in select circumstances, either on demand or in a CI (`Jenkinsfile`) branch running on a VM?

**Comment by jglick** [comment]
#661 seems to have flaked in `ToolsTest`.

**Comment by timja** [comment]
A number of flakes in https://github.com/jenkinsci/bom/pull/721/checks?check_run_id=4206726105

**Comment by jglick** [comment]
https://ci.jenkins.io/job/Tools/job/bom/job/PR-721/2/testReport/junit/org.jenkinsci.plugins.pipeline.modeldefinition/ValidatorTest/pct_pipeline_model_definition_weekly___scriptSecurityRejectionInWhenExpression/ is odd. The build hangs with

```
  36.450 [test100 #1] [Pipeline] Start of Pipeline
  36.651 [test100 #1] [Pipeline] node
  51.661 [test100 #1] Still waiting to schedule task
  51.662 [test100 #1] ‘slave0’ is offline
 509.338 [id=7130]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Periodic background build discarder
 509.341 [id=7130]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Periodic background build discarder. 3 ms
 600.001 [id=1]	WARNING	o.j.hudson.test.JenkinsRule$2#evaluate: Test timed out (after 600 seconds).
```

Yet https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/3f496434de4cf2fb618bf85d4fa306978a485630/pipeline-model-definition/src/test/java/org/jenkinsci/plugins/pipeline/modeldefinition/ValidatorTest.java#L68 waits for the agent to come online before any tests even start. So I infer that the agent went _offline_ at some point, without leaving any trace in the logs. Perversely (I guess something odd with `@ClassRule`) _passing_ tests like https://ci.jenkins.io/job/Tools/job/bom/job/PR-721/2/testReport/junit/org.jenkinsci.plugins.pipeline.modeldefinition/ValidatorTest/pct_pipeline_model_definition_2_319_x___agentMissingRequiredParam/ have a fuller log, with 100 previous tests passing—though in a successful suite run, this is only the third test to actually use the agent.

My only clue is from https://ci.jenkins.io/job/Tools/job/bom/job/PR-721/2/testReport/org.jenkinsci.plugins.pipeline.modeldefinition/ParallelTest/pct_pipeline_model_definition_weekly___parallelStagesAgentEnvWhen/ which preserves

```
  42.314 [test5 #1] Still waiting to schedule task
  42.314 [test5 #1] ‘slave1’ is offline
 137.187 [id=1049]	INFO	h.r.SynchronousCommandTransport$ReaderThread#run: I/O error in channel slave0
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2799)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3274)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:934)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:396)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
 600.001 [id=1]	WARNING	o.j.hudson.test.JenkinsRule$2#evaluate: Test timed out (after 600 seconds).
```

suggesting that the agent JVM is hung, or the socket is closed, etc.
