### ISSUE TITLE
`AxisTest` fails with cryptic PCT-only errors

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#615]
See [#251 (comment)](https://github.com/jenkinsci/bom/pull/251#issuecomment-645012427). It would be good to get to the bottom of this and remove the `AxisTest` exclusion.

**Comment by basil** [comment]
The `AxisTest` exclusion ought to be removed, as its presence has led to breaking changes not being discovered quickly enough in the recent past. The blocking issue is a PCT-only failure of `AxisTest#submitInvalidAxisValue`:

```
org.htmlunit.ElementNotFoundException: elementName=[input] attributeName=[name] attributeValue=[_.valueString]
	at org.htmlunit.html.HtmlForm.getInputByName(HtmlForm.java:636)
	at hudson.matrix.AxisTest.submitInvalidAxisValue(AxisTest.java:94)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:607)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The problem can be reproduced outside of PCT by checking out `matrix-project-plugin` and adding the Git plugin to test scope

```xml
diff --git a/pom.xml b/pom.xml
index a9bdf84..7d13f0c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -74,6 +74,11 @@
             <artifactId>mockito-core</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.jenkins-ci.plugins</groupId>
+            <artifactId>git</artifactId>
+            <scope>test</scope>
+        </dependency>
     </dependencies>
     <dependencyManagement>
         <dependencies>
```

then running `mvn clean verify -Dtest=AxisTest#submitInvalidAxisValue`. It seems like this is a simple test issue that should be relatively easy to fix. Once a fix has been integrated and released, this long-standing exclusion can finally be removed.

**Comment by basil** [comment]
FYI @MarkEWaite since the above failure only occurs when the Git plugin is on the test classpath

**Comment by MarkEWaite** [comment]
It appears that the test relies on a lookup of the input form by name but the name is ambiguous when the git plugin is loaded.  The test finds an input for by name("_.name").  Without the git plugin loaded, there is only one form with that name on the page.  With the git plugin loaded, there is another form with that same name and the form from the git plugin is selected instead of the form from the matrix project plugin.

Maybe an XPath selection could be used instead of finding the input form by name?

I'll need to do more searching as time allows.

**Comment by basil** [comment]
> Maybe an XPath selection could be used instead of finding the input form by name?

Seems like a good idea. For what it's worth, I think ChatGPT is pretty good at writing XPath queries.

**Comment by MarkEWaite** [comment]
> As of #2767 at least 1 out of 4 tests is running on a regular basis. Now _this_ I call progress.

Thanks so much for #2767 and the adjustment of the exclusions so that one of the tests is being watched.
