### ISSUE TITLE
`JobPropertyStepTest` had been ignored for one reason but is now failing for another reason

### ISSUE THREAD

**Issue by basil** [jenkinsci/bom#811]
### Jenkins and plugins versions report

Pipeline: Multibranch 696.v52535c46f4c9

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.3 LTS x86_64

### Reproduction steps

- Remove any exclusions for `JobPropertyStepTest`, if any remain in the source tree.
- Run: `PLUGINS=workflow-multibranch TEST=org.jenkinsci.plugins.workflow.multibranch.JobPropertyStepTest#configRoundTripParameters bash local-test.sh`

### Expected Results

The test passes.

### Actual Results

This regression went noticed because these test results were being ignored for a different reason (jenkinsci/workflow-multibranch-plugin#128). That PR was merged, but the test results were never un-ignored, so this new regression slipped by unnoticed.

This test now fails with:

```java
java.lang.AssertionError: expected:<1> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.jenkinsci.plugins.workflow.multibranch.JobPropertyStepTest.configRoundTripParameters(JobPropertyStepTest.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:601)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jglick** [comment]
https://github.com/jenkinsci/workflow-multibranch-plugin/blob/ff76c0c399ac473145c10d350613f03d985430e6/src/test/java/org/jenkinsci/plugins/workflow/multibranch/JobPropertyStepTest.java#L112-L116 not using a helpful assertion.

**Comment by jglick** [comment]
Huh, apparently _fixes_ text can work across repositories? Was not expecting that.

**Comment by timja** [comment]
> Huh, apparently _fixes_ text can work across repositories? Was not expecting that.

it does if the person who merges it has write access on the repository you've done the `fixes ..` on
